# Generated by Django 6.0.1 on 2026-01-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comany_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('job_salary', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('job_requried_skills', models.TextField()),
                ('job_location', models.CharField(max_length=255)),
                ('job_apply_link', models.URLField()),
                ('posted_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_file', models.FileField(upload_to='resumes/')),
            ],
        ),
    ]
