# Generated by Django 6.0.1 on 2026-01-17 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobDescription',
            new_name='Job',
        ),
    ]
