# Generated by Django 6.0.1 on 2026-01-17 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_jobdescription_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='comany_name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='job_requried_skills',
            new_name='job_required_skills',
        ),
    ]
