# Generated by Django 6.0 on 2026-01-05 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_job_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='education',
        ),
    ]
