# Generated by Django 5.2.7 on 2026-01-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_job_job_apply_link_alter_job_id_alter_resume_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume',
            field=models.FileField(upload_to='resume/'),
        ),
    ]
