# Generated by Django 5.2.7 on 2026-01-06 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_resume_resume_file_alter_education_id_alter_job_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='resume',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
