# Generated by Django 5.2.7 on 2026-01-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_skill_resume_delete_education_delete_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applylink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
